apiVersion: v2
appVersion: 0.18.0
description: A Helm chart for NATS Streaming
icon: https://nats.io/img/nats-icon-color.png
keywords:
- nats
- streaming
- stan
- delivery
- ratelimit
- replay
- statefulset
- cncf
name: stan
version: 0.4.2
