apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" .}}-config
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: ververica-platform
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    system: ververica-platform
    {{- with .Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
data:
  application-prod-user.yaml: |
{{- include "vvp.application.config" . | nindent 4}}
