{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- with .Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.rbac.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.rbac.imagePullSecret }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- with .Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "pods", "services", "secrets", "serviceaccounts"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- with .Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}
roleRef:
  kind: Role
  name: {{ template "fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- /*

IMPORTANT: Role and RoleBinding below always be in sync with the ones above.

*/ -}}
{{- if .Values.rbac.additionalNamespaces }}
{{- $root := . -}}
{{- range .Values.rbac.additionalNamespaces }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fullname" $ }}
  namespace: {{ . }}
  labels:
    {{- with $root.Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "pods", "services", "secrets", "serviceaccounts"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fullname" $ }}
  namespace: {{ . }}
  labels:
    {{- with $root.Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" $ }}
  namespace: "{{ $root.Release.Namespace }}"
roleRef:
  kind: Role
  name: {{ template "fullname" $ }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
