{{- if .Values.samlCredentials -}}
{{- if not .Values.samlCredentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" .}}-saml-credentials
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: ververica-platform
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    system: ververica-platform
    {{- with .Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- $config := .Values.samlCredentials }}
  {{ include "vvp.saml.creds.secret.value" (dict "config" $config "key" "certificate") }}
{{- end }}
{{- end -}}
