{{- $bootstrapToken := include "vvp.bootstrap.token" . -}}
{{- if $bootstrapToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" .}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: ververica-platform
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    system: ververica-platform
    {{- with .Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  bootstrapToken: {{ b64enc $bootstrapToken }}
{{- end -}}
