apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: ververica-platform
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    system: ververica-platform
    {{- with .Values.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.labels }}
    {{ . | toYaml | nindent 4}}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ . | toYaml | nindent 4}}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ template "fullname" . }}
    component: ververica-platform
